# Model creation

## Libs

In [1]:
from prepareRSSI import RssiDatas
import pandas as pd
import parameters as param
import numpy as np

## Import the RSSI, mac and zones values

In [22]:
RSSI = RssiDatas()

#df = pd.read_csv(param.rssi_csv_output)
#df.head(100)

rssi_tmp = np.genfromtxt(param.rssi_csv_output, delimiter=',')
# deleting index column and row :
rssi_tmp = np.delete(rssi_tmp, 0, 1)
RSSI.rssi = np.delete(rssi_tmp, 0, 0)

print("RSSI :\n",RSSI.rssi)

mac_tmp = np.genfromtxt(param.mac_csv_output, delimiter=',')
# deleting index column and row :
print("mac :\n",mac_tmp)

RSSI.mac = np.delete(mac_tmp, 0, 0)

print("mac :\n",RSSI.mac)

zones_tmp = np.genfromtxt(param.zones_csv_output, delimiter=',')
# deleting index column and row :
RSSI.zones = np.delete(zones_tmp, 0, 0)

print("Zones :\n",RSSI.zones)


RSSI :
 [[-67. -74. -74. ... -95. -95. -95.]
 [-67. -72. -73. ... -95. -95. -95.]
 [-67. -74. -75. ... -95. -95. -95.]
 ...
 [-79. -74. -77. ... -95. -95. -95.]
 [-76. -74. -75. ... -95. -95. -95.]
 [-77. -73. -73. ... -95. -95. -95.]]
mac :
 [[ nan   0.]
 [  0.  nan]
 [  1.  nan]
 [  2.  nan]
 [  3.  nan]
 [  4.  nan]
 [  5.  nan]
 [  6.  nan]
 [  7.  nan]
 [  8.  nan]
 [  9.  nan]
 [ 10.  nan]
 [ 11.  nan]
 [ 12.  nan]
 [ 13.  nan]
 [ 14.  nan]
 [ 15.  nan]
 [ 16.  nan]
 [ 17.  nan]
 [ 18.  nan]
 [ 19.  nan]
 [ 20.  nan]
 [ 21.  nan]
 [ 22.  nan]
 [ 23.  nan]
 [ 24.  nan]
 [ 25.  nan]
 [ 26.  nan]
 [ 27.  nan]
 [ 28.  nan]
 [ 29.  nan]
 [ 30.  nan]
 [ 31.  nan]
 [ 32.  nan]
 [ 33.  nan]
 [ 34.  nan]
 [ 35.  nan]
 [ 36.  nan]
 [ 37.  nan]
 [ 38.  nan]
 [ 39.  nan]
 [ 40.  nan]
 [ 41.  nan]
 [ 42.  nan]
 [ 43.  nan]
 [ 44.  nan]
 [ 45.  nan]
 [ 46.  nan]
 [ 47.  nan]
 [ 48.  nan]
 [ 49.  nan]
 [ 50.  nan]
 [ 51.  nan]
 [ 52.  nan]
 [ 53.  nan]
 [ 54.  nan]
 [ 55.  nan]
 [ 56.  nan]
 [ 